server:
  port: 10010
  servlet:
    encoding:
      force: true
      charset: utf-8
      enabled: true
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: question-service
          uri: lb://questionservice
          predicates:
            - Path=/question/**
        - id: focus-service
          uri: lb://focusservice
          predicates:
            - Path=/focus/**
  redis:
    host: 47.98.49.89
    port: 6378
    password: thf20021219