
server:
  port: 8082


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yuaner_community
    password: Yuaner123
    url: jdbc:mysql://rm-2vc7307rxg3bfg4rhno.mysql.cn-chengdu.rds.aliyuncs.com:3306/ms_yuaner_community_question?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
  application:
    name: questionservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 47.98.49.89
    password: thf20021219
    port: 6378

  rabbitmq:
    host: 192.168.58.130
    port: 5672
    username: yuaner
    password: thf20021219
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true