server:
  port: 8081

web:
  domain: http://localhost


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: yuaner_community
    password: Yuaner123
    url: jdbc:mysql://rm-2vc7307rxg3bfg4rhno.mysql.cn-chengdu.rds.aliyuncs.com:3306/ms_yuaner_community_user?useUnicode=true&allowMultiQueries=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource
  application:
    name: userservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
